language: ruby
rvm:
  - "1.9.3"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_26.0.1383.0.zip"
  - "unzip chromedriver_linux32_26.0.1383.0.zip"
  - "sudo mv chromedriver /usr/bin/"
